<?php

namespace ContainerXn1uG67;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SjxT6dService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Sjx_t6d' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Sjx_t6d'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'om' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'voiture' => ['privates', '.errored..service_locator.Sjx_t6d.App\\Entity\\Voiture', NULL, 'Cannot autowire service ".service_locator.Sjx_t6d": it references class "App\\Entity\\Voiture" but no such service exists.'],
        ], [
            'om' => '?',
            'voiture' => 'App\\Entity\\Voiture',
        ]);
    }
}
