<?php

namespace ContainerXn1uG67;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRechercheVoitureTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\RechercheVoitureType' shared autowired service.
     *
     * @return \App\Form\RechercheVoitureType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/RechercheVoitureType.php';

        return $container->privates['App\\Form\\RechercheVoitureType'] = new \App\Form\RechercheVoitureType();
    }
}
